In [1]:
import pandas as pd
import numpy as np

In [2]:
dataset= pd.read_csv('updated_pollution_dataset.csv')
dataset

,Temperature,Humidity,PM2.5,PM10,NO2,SO2,CO,Proximity_to_Industrial_Areas,Population_Density,Air Quality
0,29.8,59.1,5.2,17.9,18.9,9.2,1.72,6.3,319,Moderate
1,28.3,75.6,2.3,12.2,30.8,9.7,1.64,6.0,611,Moderate
2,23.1,74.7,26.7,33.8,24.4,12.6,1.63,5.2,619,Moderate
3,27.1,39.1,6.1,6.3,13.5,5.3,1.15,11.1,551,Good
4,26.5,70.7,6.9,16.0,21.9,5.6,1.01,12.7,303,Good
...,...,...,...,...,...,...,...,...,...,...
4995,40.6,74.1,116.0,126.7,45.5,25.7,2.11,2.8,765,Hazardous
4996,28.1,96.9,6.9,25.0,25.3,10.8,1.54,5.7,709,Moderate
4997,25.9,78.2,14.2,22.1,34.8,7.8,1.63,9.6,379,Moderate
4998,25.3,44.4,21.4,29.0,23.7,5.7,0.89,11.6,241,Good
4999,24.1,77.9,81.7,94.3,23.2,10.5,1.38,8.3,461,Moderate

In [3]:
from sklearn.preprocessing import OrdinalEncoder
np.random.seed(0)

data = {
    'Temperature': np.random.uniform(20, 40, size=5000), 
    'Humidity': np.random.uniform(30, 100, size=5000),     
    'PM2.5': np.random.uniform(0, 150, size=5000),         
    'PM10': np.random.uniform(0, 150, size=5000),         
    'NO2': np.random.uniform(0, 50, size=5000),            
    'SO2': np.random.uniform(0, 30, size=5000),           
    'CO': np.random.uniform(0, 5, size=5000),              
    'Proximity_to_Industrial_Areas': np.random.uniform(0, 20, size=5000), 
    'Population_Density': np.random.randint(100, 1000, size=5000),         
    'Air Quality': np.random.choice(['Good', 'Moderate', 'Hazardous'], size=5000)  
}

dataset = pd.DataFrame(data)

encoder = OrdinalEncoder(categories=[['Good', 'Moderate', 'Hazardous']])

dataset['Air Quality Encoded'] = encoder.fit_transform(dataset[['Air Quality']])

print(dataset.head())

   Temperature   Humidity       PM2.5        PM10        NO2        SO2  \
0    30.976270  55.674615  112.240197   57.920679  19.608648  26.436099
1    34.303787  50.833693   27.030406  106.871489   2.057829  15.936631
2    32.055268  34.801971   58.353472   87.147801  46.165028  26.041725
3    30.897664  54.676927    5.640027   69.470661  20.311749  23.326772
4    28.473096  46.253723    1.768161  141.546894  47.214109  29.079634

         CO  Proximity_to_Industrial_Areas  Population_Density Air Quality  \
0  3.790627                      15.818388                 372    Moderate
1  2.516593                       5.650029                 509   Hazardous
2  0.885083                       0.555929                 643        Good
3  4.162683                       2.909943                 440   Hazardous
4  2.584124                      12.985260                 685        Good

   Air Quality Encoded
0                  1.0
1                  2.0
2                  0.0
3                  2.0
4                  0.0

In [4]:
dataset

,Temperature,Humidity,PM2.5,PM10,NO2,SO2,CO,Proximity_to_Industrial_Areas,Population_Density,Air Quality,Air Quality Encoded
0,30.976270,55.674615,112.240197,57.920679,19.608648,26.436099,3.790627,15.818388,372,Moderate,1.0
1,34.303787,50.833693,27.030406,106.871489,2.057829,15.936631,2.516593,5.650029,509,Hazardous,2.0
2,32.055268,34.801971,58.353472,87.147801,46.165028,26.041725,0.885083,0.555929,643,Good,0.0
3,30.897664,54.676927,5.640027,69.470661,20.311749,23.326772,4.162683,2.909943,440,Hazardous,2.0
4,28.473096,46.253723,1.768161,141.546894,47.214109,29.079634,2.584124,12.985260,685,Good,0.0
...,...,...,...,...,...,...,...,...,...,...,...
4995,24.363115,68.531277,50.142318,112.226176,16.992593,18.670776,4.881804,13.367662,408,Good,0.0
4996,24.709070,57.800593,29.324770,44.739992,30.630801,15.934213,0.547341,19.898229,273,Good,0.0
4997,23.947765,83.090066,79.864495,66.968364,33.309100,25.587126,2.860383,11.764478,239,Moderate,1.0
4998,27.973744,31.665120,56.117511,54.018992,47.512556,22.026887,2.497235,8.492298,883,Hazardous,2.0
4999,39.171862,86.950256,16.006795,93.882997,9.650541,19.169922,4.790436,18.032654,270,Moderate,1.0

In [5]:
dataset=dataset.drop("Air Quality",axis=1)
dataset

,Temperature,Humidity,PM2.5,PM10,NO2,SO2,CO,Proximity_to_Industrial_Areas,Population_Density,Air Quality Encoded
0,30.976270,55.674615,112.240197,57.920679,19.608648,26.436099,3.790627,15.818388,372,1.0
1,34.303787,50.833693,27.030406,106.871489,2.057829,15.936631,2.516593,5.650029,509,2.0
2,32.055268,34.801971,58.353472,87.147801,46.165028,26.041725,0.885083,0.555929,643,0.0
3,30.897664,54.676927,5.640027,69.470661,20.311749,23.326772,4.162683,2.909943,440,2.0
4,28.473096,46.253723,1.768161,141.546894,47.214109,29.079634,2.584124,12.985260,685,0.0
...,...,...,...,...,...,...,...,...,...,...
4995,24.363115,68.531277,50.142318,112.226176,16.992593,18.670776,4.881804,13.367662,408,0.0
4996,24.709070,57.800593,29.324770,44.739992,30.630801,15.934213,0.547341,19.898229,273,0.0
4997,23.947765,83.090066,79.864495,66.968364,33.309100,25.587126,2.860383,11.764478,239,1.0
4998,27.973744,31.665120,56.117511,54.018992,47.512556,22.026887,2.497235,8.492298,883,2.0
4999,39.171862,86.950256,16.006795,93.882997,9.650541,19.169922,4.790436,18.032654,270,1.0

In [6]:
dataset.columns

Index(['Temperature', 'Humidity', 'PM2.5', 'PM10', 'NO2', 'SO2', 'CO',
       'Proximity_to_Industrial_Areas', 'Population_Density',
       'Air Quality Encoded'],
      dtype='object')

In [7]:
indep= dataset[['Temperature', 'Humidity', 'PM2.5', 'PM10', 'NO2', 'SO2', 'CO',
       'Proximity_to_Industrial_Areas', 'Population_Density']]
dep= dataset[['Air Quality Encoded']]

In [8]:
dataset['Air Quality Encoded'].value_counts()

0.0    1690
1.0    1682
2.0    1628
Name: Air Quality Encoded, dtype: int64

In [9]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test= train_test_split(indep, dep, test_size=0.30,random_state=0)

In [10]:
from sklearn.tree import DecisionTreeClassifier
classifier= DecisionTreeClassifier()
classifier.fit(x_train,y_train)

DecisionTreeClassifier()

In [11]:
y_pred= classifier.predict(x_test)

In [12]:
from sklearn.metrics import confusion_matrix
con_mat= confusion_matrix(y_test,y_pred)
con_mat

array([[151, 175, 177],
       [170, 170, 188],
       [137, 158, 174]], dtype=int64)

In [13]:
print(con_mat)

[[151 175 177]
 [170 170 188]
 [137 158 174]]

In [14]:
from sklearn.metrics import classification_report
class_report=classification_report(y_test,y_pred)
print(class_report)

              precision    recall  f1-score   support

         0.0       0.33      0.30      0.31       503
         1.0       0.34      0.32      0.33       528
         2.0       0.32      0.37      0.35       469

    accuracy                           0.33      1500
   macro avg       0.33      0.33      0.33      1500
weighted avg       0.33      0.33      0.33      1500

In [15]:
classifier.predict([[30.97,55.67,112.2,57.92,19.60,26.43,3.7,15.818,372]])

C:\Users\haish\anaconda3\envs\aiml\lib\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  "X does not have valid feature names, but"

array([1.])